Repository ArkEcosystem/docs, pull requests merged in 2019-12, with the labels that each got.

#498 docs: update desktop wallet plugins
  docs/guidebook/guides/desktop.md
Labels: Complexity: Medium, Type: Documentation

#500 Devnet setup
  docs/tutorials/node/setupdevnet.md
Labels: Complexity: High, Status: Member Approved

#502 chore(desktop wallet): rm delegate reg. ledger task
  docs/guidebook/release-guidelines/going-live.md
Labels: Complexity: Low, Type: Task

#504 chore: add devnet setup to navigation
  docs/.vuepress/sidebars/tutorials.js
Labels: Complexity: Low, Type: Task
