Repository ArkEcosystem/docs, pull requests merged in 2019-08, with the labels that each got.

#458 chore: fix inconsistent whitespace
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Medium, Status: Member Approved, Type: Task

#461 fix: how to write custom transaction compatible with develop branch
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Medium, Status: In Progress, Status: Member Approved, Type: Bugfix

#454 Updating Javascript Examples
  docs/sdk/clients/usage.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved

#453 Updating Javascript examples
  docs/guidebook/developer/send-transaction.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved

#460 docs(tutorials): replace forum.ark.io with arkdelegates.io in voting guide
  docs/tutorials/usage-guides/how-to-vote-in-the-ark-desktop-wallet.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved, Type: Documentation

#455 Update Laravel Framework Typo
  docs/sdk/frameworks/laravel.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#465 docs(guidebook): add desktop wallet plugin documentation
  docs/guidebook/guides/desktop.md
Labels: Complexity: High, Type: Documentation
