Repository ArkEcosystem/docs, pull requests merged in 2019-09, with the labels that each got.

#469 chore: add/move deprecated packages
  docs/.vuepress/sidebars/guidebook.js
  docs/guidebook/core/plugins/deprecated/README.md
  docs/guidebook/core/plugins/deprecated/core-database-sequelize.md
  docs/guidebook/core/plugins/deprecated/core-graphql.md
  docs/guidebook/core/plugins/deprecated/core-json-rpc.md
  docs/guidebook/core/plugins/deprecated/core-snapshots-cli.md
  docs/guidebook/core/plugins/deprecated/core-transaction-pool-redis.md
  docs/guidebook/core/plugins/optional/README.md
Labels: Bounty: Tier 6, Complexity: Medium, Status: Contributor Approved, Type: Task

#470 feat: add explanation on running explorer in different ways
  docs/guidebook/guides/explorer.md
Labels: Complexity: Low, Type: Feature

#472 docs: Updated a deprecated ssl directive in secure.md
  docs/tutorials/node/secure.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved

#467 fix: proper casing in circleci badges
  docs/guidebook/guides/desktop.md
  docs/guidebook/guides/explorer.md
  docs/guidebook/guides/mobile.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#474 docs(guidebook): update list of events location
  docs/guidebook/core/plugins/required/core-event-emitter.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Documentation

#475 ci: setup github action workflow for build
  .circleci/config.yml
  .github/workflows/build.yml
Labels: Complexity: Low

#477 fix: plugin order instructions
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Low, Status: Contributor Approved

#476 fix: typo
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#486 Update secure.md
  docs/tutorials/node/secure.md
Labels: Complexity: Low, Status: Member Approved
