Repository ArkEcosystem/docs, pull requests merged in 2019-01, with the labels that each got.

#223 docs: update responses examples
  docs/api/public/v2/blocks.md
  docs/api/public/v2/delegates.md
  docs/api/public/v2/node.md
  docs/api/public/v2/peers.md
  docs/api/public/v2/transactions.md
  docs/api/public/v2/votes.md
  docs/api/public/v2/wallets.md
Labels: :moneybag: Bounty T5

#224 docs: add and fix go client examples
  docs/sdk/clients/go.md
  docs/sdk/examples/sdk-demos.md
Labels: :moneybag: Bounty T4

#228 docs: update labels for repository management
  docs/guidebook/contribution-guidelines/repository-management.md
Labels: :crossed_swords: do not merge, in progress

#229 docs: add missing authors to desktop wallet
  docs/guidebook/guides/desktop.md
Labels: Type: Documentation, in progress

#231 fix: wrong derivation source of wallet address
  docs/guidebook/core/data-models.md
Labels: Bounty: Tier 6

#230 fix: broken link to event-emitter getEvents method
  docs/guidebook/core/plugins/core-event-emitter.md
Labels: Bounty: Tier 6, in progress

#225 docs: update delegates and transactions missing endpoints
  docs/api/public/v2/delegates.md
  docs/api/public/v2/transactions.md
Labels: Type: Documentation

#244 docs: move legacy content to archived section
  docs/.vuepress/config.js
  docs/.vuepress/sidebars/api/public.js
  docs/.vuepress/sidebars/archive.js
  docs/.vuepress/sidebars/main.js
  docs/api/README.md
  docs/api/json-rpc/README.md
  docs/api/public/README.md
  docs/api/public/troubleshooting.md
  docs/api/public/v2/blocks.md
  docs/api/public/v2/delegates.md
  docs/api/public/v2/node.md
  docs/api/public/v2/peers.md
  docs/api/public/v2/transactions.md
  docs/api/public/v2/votes.md
  docs/api/public/v2/wallets.md
  docs/api/public/versions.md
  docs/api/webhooks/README.md
  docs/archive/README.md
  docs/archive/api/public-v1/README.md
  docs/archive/api/public-v1/accounts.md
  docs/archive/api/public-v1/blocks.md
  docs/archive/api/public-v1/delegates.md
  docs/archive/api/public-v1/loader.md
  docs/archive/api/public-v1/peers.md
  docs/archive/api/public-v1/signatures.md
  docs/archive/api/public-v1/transactions.md
Labels: Type: Documentation

#247 fix: update the instructions to use Docker in Core
  docs/guidebook/core/docker.md
Labels: Type: Documentation

#256 fix: installation of separate libs
  docs/sdk/cryptography/usage.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Bugfix
