Repository ArkEcosystem/docs, pull requests merged in 2019-04, with the labels that each got.

#364 docs(guidebook): add a comment section to the contribution guidelines
  docs/guidebook/contribution-guidelines/clean-code-and-tests.md
Labels: Complexity: Low, Type: Documentation

#365 docs: remove active delegates endpoint
  docs/api/public/v2/delegates.md
Labels: Bounty: Tier 6, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#366 docs: update CLI documentation
  docs/guidebook/core/cli.md
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#367 docs: C++ minor improvements
  docs/guidebook/developer/send-transaction.md
  docs/sdk/clients/usage.md
Labels: Complexity: Low, Type: Documentation

#371 feat: add styles to details/summary
  docs/.vuepress/styles/index.styl
  docs/guidebook/guides/desktop.md
  docs/tutorials/iot/boards/esp32-adafruit/README.md
  docs/tutorials/iot/boards/esp8266-adafruit/README.md
Labels: Bounty: Tier 3, Complexity: Medium, Status: Contributor Approved, Type: Feature

#372 docs: rework esp32 and esp8266 pages
  docs/.vuepress/styles/index.styl
  docs/tutorials/iot/boards/esp32-adafruit/README.md
  docs/tutorials/iot/boards/esp8266-adafruit/README.md
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-1.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-2.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-3.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-4.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-5.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-6.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-7.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-8.jpeg
  docs/tutorials/iot/drivers/assets/cp2104/cp2104-usb-driver-9.jpeg
  docs/tutorials/iot/drivers/cp2104/README.md
Labels: Bounty: Tier 4, Complexity: High, Status: Contributor Approved, Type: Documentation

#375 docs: add blockchain endpoint
  docs/.vuepress/sidebars/api/public.js
  docs/api/public/v2/blockchain.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Documentation

#376 docs: removes changelogs
  docs/.vuepress/sidebars/releases.js
  docs/releases/README.md
  docs/releases/v2.0.19/changelog.md
  docs/releases/v2.1/README.md
  docs/releases/v2.1/changelog.md
  docs/releases/v2.1/changes.md
  docs/releases/v2.2/changelog.md
  docs/releases/v2.3/changelog.md
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#377 docs: adjust tables
  docs/api/json-rpc/blocks.md
  docs/api/json-rpc/transactions.md
  docs/api/json-rpc/wallets.md
  docs/api/p2p/README.md
  docs/api/public/v2/blocks.md
  docs/api/public/v2/delegates.md
  docs/api/public/v2/peers.md
  docs/api/public/v2/transactions.md
  docs/api/public/v2/votes.md
  docs/api/public/v2/wallets.md
  docs/api/webhooks/README.md
  docs/archive/api/public-v1/accounts.md
  docs/archive/api/public-v1/blocks.md
  docs/archive/api/public-v1/delegates.md
  docs/archive/api/public-v1/peers.md
  docs/archive/api/public-v1/transactions.md
  docs/cryptography/README.md
  docs/exchanges/json-rpc.md
  docs/exchanges/relay.md
  docs/guidebook/contribution-guidelines/writing-documentation.md
  docs/guidebook/core/cli.md
  docs/guidebook/core/configuration.md
  docs/guidebook/core/plugins/deprecated/README.md
  docs/guidebook/core/plugins/optional/README.md
  docs/guidebook/core/plugins/required/README.md
  docs/introduction/ark/what-is-an-ark-address.md
  docs/releases/v2.0.19/README.md
  docs/releases/v2.1/changes.md
  docs/releases/v2.1/migrating_2.0_2.1.md
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Bounty: Tier 4, Complexity: High, Status: Contributor Approved, Type: Documentation

#378 misc: add space before opening parens and capitalization
  docs/README.md
  docs/archive/tutorials/dynamic-fees.md
  docs/cryptography/README.md
  docs/exchanges/docker.md
  docs/exchanges/relay.md
  docs/faq/desktop-wallet.md
  docs/glossary/README.md
  docs/guidebook/contribution-guidelines/writing-documentation.md
  docs/guidebook/core/cli.md
  docs/guidebook/core/logging.md
  docs/introduction/ark/ark-network-topology.md
  docs/introduction/blockchain/when-do-you-need-blockchain.md
  docs/iot/README.md
  docs/releases/v2.0.19/README.md
  docs/sdk/clients/usage.md
  docs/sdk/cryptography/usage.md
  docs/sdk/examples/sdk-demos.md
  docs/security/discovering/public-disclosure.md
  docs/tutorials/iot/README.md
  docs/tutorials/iot/boards/esp32-adafruit/README.md
  docs/tutorials/iot/boards/esp8266-adafruit/README.md
  docs/tutorials/iot/environment/cpp/README.md
  docs/tutorials/iot/examples/arduino/client/assets/esp32.ino
  docs/tutorials/iot/examples/arduino/client/assets/esp8266.ino
  docs/tutorials/iot/examples/arduino/client/esp32/README.md
  docs/tutorials/iot/examples/arduino/client/esp8266/README.md
  docs/tutorials/iot/examples/arduino/crypto/assets/esp32.ino
  docs/tutorials/iot/examples/arduino/crypto/assets/esp8266.ino
  docs/tutorials/iot/examples/arduino/crypto/esp32/README.md
  docs/tutorials/iot/examples/arduino/crypto/esp8266/README.md
  docs/tutorials/iot/reacting-to-data-on-the-blockchain.md
  docs/tutorials/iot/storing-data-on-the-blockchain.md
  docs/tutorials/node/dynamic-fees.md
  docs/tutorials/node/secure.md
  docs/tutorials/node/setup.md
  docs/tutorials/usage-guides/how-to-use-ark-desktop-wallet.md
  docs/tutorials/usage-guides/how-to-use-ark-mobile-wallet.md
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved

#379 docs: update bounties page
  docs/faq/bounties.md
  docs/releases/v2.3/README.md
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#382 Docs/release update
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Complexity: Medium

#383 docs(api): add example curl commands to blockchain and delegates pages
  docs/api/public/v2/blockchain.md
  docs/api/public/v2/delegates.md
Labels: Complexity: High

#384 docs: refactored migration guide
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Complexity: Low, Type: Documentation

#386 docs: Adding GSoD documentation section for the program application
  docs/guidebook/contribution-guidelines/gsod.md
  docs/guidebook/contribution-guidelines/writing-documentation.md
Labels: Complexity: Medium

#387 docs: remove redundant step
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Complexity: Low, Type: Documentation

#388 chore: add google docs banner
  docs/guidebook/contribution-guidelines/assets/gsod-banner.png
  docs/guidebook/contribution-guidelines/gsod.md
Labels: Complexity: Low

#389 docs: typo code section
  docs/exchanges/rate-limiting.md
Labels: Complexity: Low, Type: Documentation

#390 chore: title case of new article
  docs/faq/bounties.md
  docs/guidebook/contribution-guidelines/gsod.md
  docs/guidebook/contribution-guidelines/writing-documentation.md
  docs/releases/v2.3/migrating_2.2_2.3.md
  docs/tutorials/iot/reacting-to-data-on-the-blockchain.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#391 docs: fix bold warning
  docs/guidebook/developer/send-transaction.md
Labels: Complexity: Low, Type: Documentation

#393 docs: adjusting java demo to the recent changes
  docs/sdk/examples/sdk-demos.md
Labels: Complexity: Low, Type: Documentation
