Repository ArkEcosystem/docs, pull requests merged in 2019-03, with the labels that each got.

#289 docs: replace lerna bootstrap call with yarn setup
  docs/releases/v2.1/migrating_1.0_2.1.md
Labels: Complexity: Low, Type: Documentation

#288 docs(releases): 2.2 upgrade guide
  docs/.vuepress/sidebars/releases.js
  docs/guidebook/core/cli.md
  docs/releases/v2.0.19/changelog.md
  docs/releases/v2.1/changelog.md
  docs/releases/v2.2/README.md
  docs/releases/v2.2/changelog.md
  docs/releases/v2.2/migrating_2.1_2.2.md
Labels: Complexity: Medium, Status: In Progress, Type: Documentation

#290 docs: Update Cpp Examples
  docs/faq/bounties.md
  docs/guidebook/developer/send-transaction.md
  docs/sdk/clients/usage.md
  docs/sdk/cryptography/usage.md
  docs/sdk/examples/sdk-demos.md
Labels: Complexity: High, Type: Documentation

#291 docs: More Cpp Improvements
  docs/sdk/clients/usage.md
  docs/sdk/cryptography/usage.md
Labels: Complexity: Medium, Type: Documentation

#293 docs: remove v1 code from clients
  docs/releases/v2.1/migrating_2.0_2.1.md
  docs/releases/v2.2/migrating_2.1_2.2.md
  docs/sdk/clients/usage.md
  docs/sdk/cryptography/usage.md
  docs/sdk/examples/sdk-demos.md
  docs/sdk/frameworks/laravel.md
  docs/sdk/frameworks/symfony.md
Labels: Complexity: Medium, Type: Documentation

#292 docs: add new delegates search params
  docs/api/public/v2/delegates.md
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Documentation

#295 docs(guidebook): add jest matchers to core testing
  docs/guidebook/core/testing.md
Labels: Complexity: High, Type: Documentation

#286 docs: added some undocumented commands
  docs/guidebook/core/cli.md
Labels: Complexity: Low, Status: Needs Changes, Status: Needs Review, Type: Documentation

#296 docs(guidebook): add troubleshooting for an unknown core state via CLI
  docs/guidebook/core/cli.md
  docs/guidebook/core/testing.md
Labels: Complexity: Low, Type: Documentation

#297 docs(guidebook): update samples and directories for "How to Setup You…
  docs/guidebook/core/testing.md
  docs/guidebook/developer/setup-dev-environment.md
Labels: Complexity: Medium, Type: Documentation

#298 docs(guidebook): update the code samples for "Examining the Node Lifecycle"
  docs/guidebook/core/node-lifecycle.md
  docs/guidebook/developer/setup-dev-environment.md
Labels: Complexity: High, Type: Documentation

#299 docs(guidebook): add CLI and 2.2 upgrade warnings
  docs/guidebook/core/cli.md
  docs/releases/v2.2/migrating_2.1_2.2.md
Labels: Complexity: High, Type: Documentation

#300 docs: update guidebook/core/testing
  docs/guidebook/core/testing.md
Labels: Complexity: Medium, Type: Documentation

#304 docs(guidebook): Add high level description of the peer verifier
  docs/.vuepress/sidebars/guidebook.js
  docs/guidebook/core/source-code.md
Labels: Complexity: Low, Type: Documentation

#301 docs(api): update the node configuration response
  docs/api/public/v2/node.md
Labels: Complexity: Medium, Type: Documentation

#305 docs(api): update the post transaction response and add 'read more' link
  docs/api/public/v2/transactions.md
Labels: Complexity: Low, Type: Documentation

#302 docs(guidebook): fix typo
  docs/guidebook/README.md
  docs/guidebook/core/data-models.md
Labels: Complexity: Low, Type: Documentation

#306 docs(releases): add more details and troubleshooting to the 2.2 upgrade
  docs/releases/v2.2/migrating_2.1_2.2.md
Labels: Complexity: Low, Type: Documentation

#308 docs: point CLI links to master
  docs/guidebook/core/cli.md
Labels: Complexity: Low, Type: Documentation

#309 docs: Fix Cpp Demo Example
  docs/sdk/examples/sdk-demos.md
Labels: Complexity: Low, Type: Documentation

#310 docs(guidebook): update plugin installation instructions
  docs/guidebook/core/plugins/README.md
Labels: Complexity: Low, Type: Documentation

#313 docs: archive the core-commander
  docs/.vuepress/sidebars/archive.js
  docs/.vuepress/sidebars/guidebook.js
  docs/archive/guidebook/guides/core-commander.md
Labels: Complexity: Low, Type: Documentation

#315 docs(guidebook): update the plugin development section for core
  docs/guidebook/core/plugins/README.md
Labels: Complexity: Medium, Type: Documentation

#316 docs(tutorials): link to the new docker guide for node setup
  docs/tutorials/node/setup.md
Labels: Complexity: Medium, Type: Documentation

#317 chore: Update Ark Core setup guide
  docs/tutorials/node/setup.md
Labels: Complexity: Medium

#320 chore: Update setting up relay node for exchanges
  docs/exchanges/relay.md
Labels: Complexity: Medium

#321 Docs/updates
  docs/exchanges/README.md
  docs/exchanges/relay.md
Labels: Complexity: Medium

#323 docs(api): add query params to the peers list endpoint
  docs/api/public/v2/peers.md
Labels: Complexity: Low, Type: Documentation

#324 docs(guidebook): update the "Write a Plugin" instructions and samples
  docs/guidebook/core/plugins/README.md
  docs/guidebook/developer/write-a-plugin.md
Labels: Complexity: High, Type: Documentation

#325 docs(guidebook): mention GitHub keywords in the contribution guidelines
  docs/guidebook/contribution-guidelines/contributing.md
Labels: Complexity: Low, Type: Documentation

#327 docs(guidebook): remove reference to yarn start command
  docs/guidebook/core/development.md
Labels: Bounty: Tier 1, Complexity: Low, Status: Contributor Approved, Type: Documentation

#331 docs: add plugin development docs and fix dead links
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  docs/.vuepress/sidebars/guidebook.js
  docs/.vuepress/sidebars/tutorials.js
  docs/archive/tutorials/dynamic-fees.md
  docs/exchanges/relay.md
  docs/guidebook/core/development.md
  docs/guidebook/core/plugins/README.md
  docs/guidebook/developer/monitor-blockchain.md
  docs/guidebook/guides/mobile.md
  docs/security/discovering/public-disclosure.md
  docs/tutorials/core/plugins/how-to-create-http-servers.md
  docs/tutorials/core/plugins/how-to-interact-with-events.md
  docs/tutorials/core/plugins/how-to-interact-with-the-blockchain.md
  docs/tutorials/core/plugins/how-to-interact-with-the-database.md
  docs/tutorials/core/plugins/how-to-interact-with-wallets.md
  docs/tutorials/core/plugins/how-to-write-a-core-plugin.md
  docs/tutorials/deployer/azure.md
  docs/tutorials/node/dynamic-fees.md
  docs/tutorials/node/setup.md
  docs/tutorials/usage-guides/how-to-use-ark-explorer.md
Labels: Complexity: High, Type: Documentation

#332 docs(releases): add release channel information
  docs/releases/README.md
Labels: Complexity: Low, Type: Documentation

#333 docs(releases): add 2.3 to the release section
  docs/.vuepress/sidebars/releases.js
  docs/releases/README.md
  docs/releases/v2.3/README.md
  docs/releases/v2.3/changelog.md
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Complexity: Medium, Type: Documentation

#334 docs: debranding configuration
  docs/guidebook/core/configuration.md
Labels: Complexity: Low, Type: Documentation

#335 docs: def value RPC
  docs/guidebook/core/configuration.md
Labels: Complexity: Low, Type: Documentation

#336 docs: remove refs to python voter balance endpoint
  docs/sdk/clients/usage.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Documentation

#337 docs(tutorials): transaction pool info for core plugins
  docs/.vuepress/sidebars/tutorials.js
  docs/tutorials/core/plugins/how-to-interact-with-the-transaction-pool.md
Labels: Complexity: Medium, Type: Documentation

#338 chore: remove voter balances endpoint description
  docs/api/public/v2/delegates.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Task

#339 docs(crypto): Cryptography Section
  docs/.vuepress/sidebars/main.js
  docs/README.md
  docs/cryptography/README.md
  docs/cryptography/assets/address.svg
  docs/cryptography/assets/address_transparent.png
  docs/cryptography/assets/overview.svg
  docs/cryptography/assets/overview_transparent.png
  docs/cryptography/assets/passphrase.svg
  docs/cryptography/assets/passphrase_transparent.png
  docs/cryptography/assets/privatekey.svg
  docs/cryptography/assets/privatekey_transparent.png
  docs/cryptography/assets/publickey.svg
  docs/cryptography/assets/publickey_transparent.png
  docs/cryptography/assets/signature.svg
  docs/cryptography/assets/signature_der.svg
  docs/cryptography/assets/signature_der_transparent.png
  docs/cryptography/assets/signature_transparent.png
  docs/cryptography/assets/wif.svg
  docs/cryptography/assets/wif_transparent.png
Labels: Complexity: High, Type: Documentation

#340 docs(tutorials): add API whitelist info the node setup guide
  docs/tutorials/node/setup.md
Labels: Complexity: Low, Type: Documentation

#341 docs(tutorials): Add public API port to UFW
  docs/tutorials/node/secure.md
Labels: Complexity: Low

#342 docs(guidebook): add live updates for docker
  docs/guidebook/core/docker.md
Labels: Complexity: Low

#345 Fix: Typo of Logger
  docs/guidebook/core/plugins/deprecated/core-logger-winston.md
Labels: Complexity: Low

#344 Fix: Typo of Logger
  docs/guidebook/core/plugins/required/core-logger.md
Labels: Complexity: Low

#348 docs(guidebook): add new error tracker packages to documentation
  docs/.vuepress/sidebars/guidebook.js
  docs/guidebook/core/plugins/deprecated/README.md
  docs/guidebook/core/plugins/deprecated/core-logger-winston.md
  docs/guidebook/core/plugins/optional/README.md
  docs/guidebook/core/plugins/optional/core-error-tracker-airbrake.md
  docs/guidebook/core/plugins/optional/core-error-tracker-raygun.md
  docs/guidebook/core/plugins/optional/core-error-tracker-rollbar.md
  docs/guidebook/core/plugins/optional/core-logger-winston.md
Labels: Complexity: Medium, Type: Documentation

#351 docs: add instructions for new aliases
  docs/releases/v2.3/migrating_2.2_2.3.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Documentation

#346 docs: update code snippets and more
  docs/.vuepress/sidebars/guidebook.js
  docs/archive/exchanges/rate-limiting.md
  docs/archive/tutorials/dynamic-fees.md
  docs/cryptography/README.md
  docs/exchanges/json-rpc-quick.md
  docs/exchanges/json-rpc.md
  docs/guidebook/core/events.md
  docs/guidebook/core/logging.md
  docs/guidebook/core/node-lifecycle.md
  docs/guidebook/core/plugins/deprecated/README.md
  docs/guidebook/core/plugins/deprecated/core-debugger-cli.md
  docs/guidebook/core/plugins/deprecated/core-graphql.md
  docs/guidebook/core/plugins/optional/core-api.md
  docs/guidebook/core/plugins/optional/core-elasticsearch.md
  docs/guidebook/core/plugins/optional/core-error-tracker-bugsnag.md
  docs/guidebook/core/plugins/optional/core-error-tracker-sentry.md
  docs/guidebook/core/plugins/optional/core-json-rpc.md
  docs/guidebook/core/plugins/optional/core-logger-winston.md
  docs/guidebook/core/plugins/optional/core-vote-report.md
  docs/guidebook/core/plugins/optional/core-webhooks.md
  docs/guidebook/core/plugins/required/core-blockchain.md
  docs/guidebook/core/plugins/required/core-database.md
  docs/guidebook/core/plugins/required/core-event-emitter.md
  docs/guidebook/core/plugins/required/core-forger.md
  docs/guidebook/core/plugins/required/core-logger.md
  docs/guidebook/core/plugins/required/core-p2p.md
  docs/guidebook/core/plugins/required/core-transaction-pool.md
  docs/guidebook/core/plugins/required/crypto.md
  docs/releases/v2.3/migrating_2.2_2.3.md
  docs/tutorials/core/plugins/how-to-interact-with-the-transaction-pool.md
  docs/tutorials/core/plugins/how-to-write-a-core-plugin.md
Labels: Bounty: Tier 2, Complexity: Undetermined, Status: Contributor Approved, Type: Documentation

#352 docs(guidebook): add release guidelines
  docs/.vuepress/sidebars/guidebook.js
  docs/guidebook/contribution-guidelines/README.md
  docs/guidebook/release-guidelines/README.md
  docs/guidebook/release-guidelines/going-live.md
  docs/guidebook/release-guidelines/releases-and-versioning.md
Labels: Complexity: Medium, Type: Documentation

#353 Extend the API blocks page
  docs/api/public/v2/README.md
  docs/api/public/v2/blocks.md
Labels: Complexity: High

#355 docs: add new events and remove eventemitter3 references
  docs/api/webhooks/README.md
  docs/guidebook/core/plugins/required/core-event-emitter.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Documentation

#356 docs(exchanges): docker instructions
  docs/exchanges/relay.md
  docs/guidebook/core/docker.md
Labels: Complexity: Medium

#357 Move Exchanges Docker into separate section
  docs/.vuepress/sidebars/exchanges.js
  docs/exchanges/README.md
  docs/exchanges/docker.md
  docs/exchanges/relay.md
Labels: Complexity: Low

#358 docs(guidebook): document new core events
  docs/guidebook/core/events.md
Labels: Complexity: Low, Type: Documentation

#359 docs(tutorials): how to use milestones
  docs/.vuepress/sidebars/tutorials.js
  docs/tutorials/core/how-to-use-milestones.md
Labels: Complexity: High, Type: Documentation

#361 docs: add active delegates endpoint
  docs/api/public/v2/delegates.md
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Documentation
