Repository ArkEcosystem/docs, pull requests merged in 2019-05, with the labels that each got.

#392 docs(releases): add 2.4.0 pages
  docs/.vuepress/sidebars/releases.js
  docs/releases/v2.4/README.md
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Medium, Status: In Progress, Type: Documentation

#396 docs(releases): add core-wallet-api instructions to 2.4.0
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Low, Type: Documentation

#402 chore: remove premature restart instructions
  docs/exchanges/relay.md
  docs/guidebook/contribution-guidelines/project-structuring.md
  docs/guidebook/core/testing.md
  docs/releases/v2.3/migrating_2.2_2.3.md
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Task

#404 chore: add CORE_DB_PORT to env config
  docs/guidebook/core/configuration.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Task

#405 docs: add config:database command
  docs/guidebook/core/cli.md
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#403 docs: how to write custom transactions
  docs/.vuepress/sidebars/tutorials.js
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: High, Status: In Progress, Type: Documentation

#409 misc: fix styling in custom transaction guide
  docs/api/public/troubleshooting.md
  docs/faq/bounties.md
  docs/faq/desktop-wallet.md
  docs/faq/passphrases.md
  docs/faq/voting-delegates.md
  docs/guidebook/contribution-guidelines/gsod.md
  docs/guidebook/core/cli.md
  docs/guidebook/core/events.md
  docs/introduction/ark/how-does-ark-smartbridge-work.md
  docs/introduction/blockchain/understanding-consensus-models.md
  docs/introduction/blockchain/what-is-blockchain.md
  docs/iot/README.md
  docs/iot/considerations.md
  docs/tutorials/core/how-to-write-custom-transactions.md
  docs/tutorials/core/plugins/how-to-write-a-core-plugin.md
  docs/tutorials/iot/environment/cpp/README.md
  docs/tutorials/node/secure.md
  docs/tutorials/usage-guides/how-to-vote-in-the-ark-desktop-wallet.md
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Type: Maintenance

#408 docs: add node/fees endpoint to api docs
  docs/api/public/v2/node.md
  docs/releases/v2.3/migrating_2.2_2.3.md
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Documentation

#407 feat: add @dated/markdown-title-case
  docs/README.md
  docs/exchanges/docker.md
  docs/guidebook/core/docker.md
  package.json
  yarn.lock
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Type: Feature

#412 docs(api): /api/node/configuration/crypto
  docs/api/public/v2/node.md
Labels: Complexity: Medium, Type: Documentation

#413 chore: 2.3 to 2.4 migrate docs whitelist issue
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Low, Type: Task

#410 misc: fixes spelling of github and replaces single quotes with apostrophes
  docs/exchanges/docker.md
  docs/exchanges/json-rpc-quick.md
  docs/faq/voting-delegates.md
  docs/guidebook/developer/tester-cli-transaction.md
  docs/guidebook/guides/mobile.md
  docs/introduction/ark/how-does-ark-smartbridge-work.md
  docs/introduction/ark/understanding-transactions-and-block-propagation.md
  docs/introduction/ark/what-is-delegated-proof-of-stake.md
  docs/introduction/blockchain/understanding-consensus-models.md
  docs/introduction/blockchain/what-is-blockchain.md
  docs/introduction/blockchain/when-do-you-need-blockchain.md
  docs/introduction/blockchain/why-do-blockchains-exist.md
  docs/releases/v2.0.19/README.md
  docs/security/discovering/public-disclosure.md
  docs/tutorials/deployer/azure.md
  docs/tutorials/iot/environment/cpp/README.md
  docs/tutorials/usage-guides/README.md
  docs/tutorials/usage-guides/how-to-use-ark-explorer.md
  docs/tutorials/usage-guides/how-to-vote-in-the-ark-desktop-wallet.md
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Type: Maintenance

#411 fix: load image from local instead of external source
  docs/iot/assets/stack_operation.png
  docs/iot/considerations.md
  docs/tutorials/iot/boards/esp32-adafruit/README.md
  docs/tutorials/iot/environment/os/README.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#406 chore: setup linting
  .eslintignore
  .eslintrc.js
  .lintstagedrc
  docs/.vuepress/components/RequestExample.vue
  docs/.vuepress/config.js
  docs/.vuepress/sidebars/api.js
  docs/.vuepress/sidebars/api/json-rpc.js
  docs/.vuepress/sidebars/api/public.js
  docs/.vuepress/sidebars/archive.js
  docs/.vuepress/sidebars/exchanges.js
  docs/.vuepress/sidebars/faq.js
  docs/.vuepress/sidebars/guidebook.js
  docs/.vuepress/sidebars/introduction.js
  docs/.vuepress/sidebars/iot.js
  docs/.vuepress/sidebars/main.js
  docs/.vuepress/sidebars/releases.js
  docs/.vuepress/sidebars/sdk.js
  docs/.vuepress/sidebars/security.js
  docs/.vuepress/sidebars/tutorials.js
  docs/.vuepress/utils/curl.js
  docs/.vuepress/utils/highlight.js
  docs/.vuepress/utils/request.js
  docs/guidebook/core/cli.md
  docs/tutorials/core/how-to-write-custom-transactions.md
  package.json
  yarn.lock
Labels: Bounty: Tier 4, Complexity: Undetermined, Status: Contributor Approved, Type: Feature

#414 docs(guidebook): update commit conventions
  docs/guidebook/contribution-guidelines/git-commit-guidelines.md
Labels: Complexity: Medium, Type: Documentation

#415 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task
