Repository ArkEcosystem/docs, pull requests merged in 2019-06, with the labels that each got.

#416 docs(releases): add core-exchange-json-rpc script to 2.4 migration
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Low, Type: Documentation

#419 fix: #417
  docs/README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#421 fix: #420
  docs/guidebook/developer/setup-dev-environment.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved

#422 chore: mark v2.4 as released
  docs/.vuepress/sidebars/releases.js
Labels: Complexity: Low, Status: In Progress, Type: Task

#423 docs(releases): copy & pasta JSON-RPC instructions
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Low, Type: Documentation

#424 docs: update migration docs for mainnet release
  docs/releases/v2.4/migrating_2.3_2.4.md
Labels: Complexity: Low, Type: Task

#426 fix: #425
  docs/iot/README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#428 fix: #427
  docs/README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#429 docs(guidebook): update setup and docker instructions for devs
  docs/guidebook/developer/setup-dev-environment.md
Labels: Complexity: Low, Type: Documentation

#432 docs(api): update API response and curl command examples
  docs/api/public/v2/blocks.md
  docs/api/public/v2/delegates.md
  docs/api/public/v2/node.md
  docs/api/public/v2/peers.md
  docs/api/public/v2/transactions.md
  docs/api/public/v2/votes.md
  docs/api/public/v2/wallets.md
Labels: Bounty: Tier 4, Complexity: Undetermined, Status: Contributor Approved

#433 docs(faq): change slack channel on /Bounties page
  docs/faq/bounties.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Documentation

#434 docs: how to write custom transactions update
  docs/guidebook/core/testing.md
  docs/tutorials/core/how-to-write-custom-transactions.md
  docs/tutorials/core/plugins/how-to-write-a-core-plugin.md
Labels: Complexity: Medium

#440 docs(exchanges): add secondary docker update option
  docs/exchanges/docker.md
  docs/guidebook/core/docker.md
Labels: Complexity: Low

#439 revert: "fix: #417"
  docs/README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#435 Add quickstart for running core tests (not just dev environment)
  docs/guidebook/developer/run-tests-for-first-time.md
  docs/guidebook/developer/setup-dev-environment.md
Labels: Bounty: Tier 3, Complexity: Low, Status: Contributor Approved

#437 docs(api): add orderBy query parameter documentation to the Public API docs
  docs/api/public/v2/blocks.md
  docs/api/public/v2/delegates.md
  docs/api/public/v2/peers.md
  docs/api/public/v2/transactions.md
  docs/api/public/v2/votes.md
  docs/api/public/v2/wallets.md
Labels: Bounty: Tier 3, Complexity: High, Status: Contributor Approved, Type: Documentation

#441 docs(pay): add reset functionality to API documentation
  docs/guidebook/guides/pay.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Documentation
