Repository ArkEcosystem/docs, pull requests merged in 2019-07, with the labels that each got.

#442 fix(cpp): correct namespace capitalization
  docs/guidebook/developer/send-transaction.md
  docs/sdk/clients/usage.md
  docs/sdk/cryptography/usage.md
  docs/sdk/examples/sdk-demos.md
  docs/tutorials/iot/boards/esp32-adafruit/README.md
  docs/tutorials/iot/boards/esp8266-adafruit/README.md
  docs/tutorials/iot/environment/cpp/README.md
  docs/tutorials/iot/examples/arduino/client/assets/esp32.ino
  docs/tutorials/iot/examples/arduino/client/assets/esp8266.ino
  docs/tutorials/iot/examples/arduino/client/esp32/README.md
  docs/tutorials/iot/examples/arduino/client/esp8266/README.md
  docs/tutorials/iot/examples/arduino/crypto/assets/esp32.ino
  docs/tutorials/iot/examples/arduino/crypto/assets/esp8266.ino
  docs/tutorials/iot/examples/arduino/crypto/esp32/README.md
  docs/tutorials/iot/examples/arduino/crypto/esp8266/README.md
  docs/tutorials/iot/reacting-to-data-on-the-blockchain.md
  docs/tutorials/iot/storing-data-on-the-blockchain.md
Labels: Complexity: Medium, Status: In Progress, Type: Bugfix

#444 docs(releases): 2.5 upgrade guide
  docs/.vuepress/sidebars/releases.js
  docs/releases/v2.5/README.md
  docs/releases/v2.5/migrating_2.4_2.5.md
Labels: Complexity: Low, Type: Documentation

#445 feat: Added Ark logo locally
  docs/.vuepress/config.js
  docs/.vuepress/public/red-corners.png
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#446 fix: How to write custom transaction
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Medium, Status: Contributor Approved, Type: Bugfix

#451 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#452 fix: logo
  docs/.vuepress/config.js
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#457 Update tutorial on how to write your own custom transactions
  docs/tutorials/core/how-to-write-custom-transactions.md
Labels: Complexity: Medium, Status: Member Approved
